### PR TITLE
Add MORE Splatoon™ songs that I liked

### PR DESCRIPTION
**Pull request by mctaylors**
Song list:
- Off the Hook - Muck Warfare — [source](https://youtu.be/Se3AuyS-gTo)
- Off the Hook - Acid Hues — [source](https://youtu.be/RoBhJth2VZE)
- Off the Hook - Shark Bytes — [source](https://youtu.be/YrGSrxDRAXU)
- DJ Octavio feat. Squid Sisters & Deep Cut - Calamari Inkantation 3MIX — [source](https://youtu.be/_TE22RCxCi4)
- Splatoon - Ink Me Up — [source](https://www.youtube.com/watch?v=LrsAKUnb3Qg)

### CODE REVIEW

**Comment by Octol1ttle** [comment]
We have enough songs in the list.

**Comment by mctaylors** [comment]
Maybe one last time? And you recently purged non-Splatoon songs... https://github.com/LabsDevelopment/Octobot/commit/9323e891a12e84e756d3ebd7d107fb885767c303

**Comment by Octol1ttle** [comment]
one last time...

**Review by Octol1ttle — APPROVED** [review]
so they really are bangers

**Pull request merged**
