### PR TITLE
/about: Add Octobot's description

### PR DESCRIPTION
**Pull request by mctaylors**
In this PR, I've added a description of Octobot to /about. Actually, /**about** is meant to have a description in it.

### CODE REVIEW

**Comment by Octol1ttle** [comment]
You haven't provided a reason for this change, this change is redundant, the description may become out of sync with the `About Me` field. This PR suffers from the same issues as #224

**Comment by mctaylors** [comment]
> the description may become out of sync with the `About Me` field.

Just so you know: this description should synchronize manually with README.md, not with the "About me" section

**Comment by Octol1ttle** [comment]
That makes the problem even worse. Having to repeat the same *three times* makes it easier to miss something being out of sync

**Comment by mctaylors** [comment]
> That makes the problem even worse. Having to repeat the same _three times_ makes it easier to miss something being out of sync

Then I should display Discord bot's name (#224) and get description from "About Me" section.

**Pull request closed without merging**
